name: Haskell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Haskell
        uses: haskell/actions/setup-haskell@v1
        with:
          ghc-version: '9.4.5'  
      - name: Install dependencies
        run: |
          cabal update
          cabal install --only-dependencies

      - name: Build project
        run: cabal build
