name: Haskell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Haskell with GHC
      uses: actions/setup-haskell@v2
      with:
        ghc-version: '8.10.7'   # حاول استخدام إصدار آخر مثل 8.10.7 بدلاً من 9.2.1
        cabal-version: '3.6.2.0'  # تحديد إصدار مناسب من cabal

    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies

    - name: Install HLint
      run: cabal install hlint

    - name: Run HLint
      run: hlint .

    - name: Build the project
      run: cabal build

    - name: Run tests
      run: cabal test
