name: Haskell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up GHC (Glasgow Haskell Compiler)
      uses: actions/setup-haskell@v2
      with:
        ghc-version: '9.2.1'

    - name: Install dependencies
      run: |
        cabal update
        cabal install --only-dependencies

    - name: Install HLint
      run: cabal install hlint

    - name: Run HLint
      run: hlint .

    - name: Build the project
      run: cabal build

    - name: Run tests
      run: cabal test
